name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Rust Version
      run: rustc --version

    - name: Rustup Update
      run: rustup update

    - name: Updated Rust Version
      run: rustc --version

    - name: Cache Cargo registry
      id: cache-cargo
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-build-cache-cargo-registry-${{ hashFiles('./Cargo.lock') }}

    - name: Cache target dir
      id: cache-target
      uses: actions/cache@v4
      with:
        path: ./target
        key: ${{ runner.os }}-build-cache-target-dir-${{ hashFiles('./Cargo.lock') }}

    - name: Check fmt
      run: cargo fmt --check

    - name: Clippy
      run: cargo clippy --no-deps -- -D warnings

    - name: Build
      run: cargo build
